version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - task
  - dependencies
  - backlog-dependencies
  registries:
  - git-github-com
